"""Contract surface: typed models and YAML IO for contracts/**/*.yaml (SPEC-E15 §2.2–2.5)."""

from __future__ import annotations

from canonic.contracts.assertions import (
    AssertionOutcome,
    assertion_to_query,
    is_executable,
    match_result,
)
from canonic.contracts.loader import (
    contracts_dir_scaffold,
    dump_assertion,
    dump_guardrail,
    dump_metric_binding,
    load_assertions,
    load_guardrails,
    load_metric_bindings,
    load_role_policy,
    load_tenancy_policy,
)
from canonic.contracts.models import (
    AllowDenyPolicy,
    AppliesTo,
    Assertion,
    AssertionExpect,
    CanonicalRef,
    ContractValidationError,
    DeprecatedAlternative,
    FinalityRule,
    Guardrail,
    GuardrailKind,
    KnowledgePolicy,
    MaskingRule,
    MaskStrategy,
    MetricBinding,
    OnMissingPrincipal,
    Realization,
    RoleDef,
    RolePolicy,
    ScopedSource,
    Severity,
    Status,
    TenancyPolicy,
    UndeclaredSource,
)
from canonic.contracts.principal import EffectivePolicy, Principal
from canonic.contracts.resolver import (
    Ambiguous,
    Binding,
    ContractResolver,
    MetricResolution,
    ScopeResolution,
    ScopeRule,
    Shared,
    Undeclared,
    Unresolved,
)
from canonic.contracts.validate import validate_contracts

__all__ = [
    "AllowDenyPolicy",
    "Ambiguous",
    "AppliesTo",
    "Assertion",
    "AssertionExpect",
    "AssertionOutcome",
    "Binding",
    "CanonicalRef",
    "ContractResolver",
    "ContractValidationError",
    "DeprecatedAlternative",
    "EffectivePolicy",
    "FinalityRule",
    "Guardrail",
    "GuardrailKind",
    "KnowledgePolicy",
    "MaskStrategy",
    "MaskingRule",
    "MetricBinding",
    "MetricResolution",
    "OnMissingPrincipal",
    "Principal",
    "Realization",
    "RoleDef",
    "RolePolicy",
    "ScopeResolution",
    "ScopeRule",
    "ScopedSource",
    "Severity",
    "Shared",
    "Status",
    "TenancyPolicy",
    "Undeclared",
    "UndeclaredSource",
    "Unresolved",
    "assertion_to_query",
    "contracts_dir_scaffold",
    "dump_assertion",
    "dump_guardrail",
    "dump_metric_binding",
    "is_executable",
    "load_assertions",
    "load_guardrails",
    "load_metric_bindings",
    "load_role_policy",
    "load_tenancy_policy",
    "match_result",
    "validate_contracts",
]
