name: 'dutch_railway_network'
version: '1.0.0'
profile: 'dutch_railway_network'

flags:
  send_anonymous_usage_stats: false

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dutch_railway_network:
    transformation:
      +docs:
        node_color: 'silver'

vars:
  execution_year: 2024
  execution_month: '202408'
  service_date: '2024-08-01'
