"""E4 ingestion & reconciliation engine (SPEC-E4)."""

from canon.ingestion.builder import (
    BuildResult,
    ContextBuilder,
    GrainDraft,
    LLMDrafter,
    NullLLMDrafter,
    SkippedEvidence,
)
from canon.ingestion.emitter import (
    AuditTrailWriter,
    ContradictionNote,
    DiffEmitter,
    DiffFormat,
    DiskEventLog,
    DiskSnapshotStore,
    EmissionResult,
    EmittedDiff,
    EventLog,
    SnapshotStore,
)
from canon.ingestion.models import (
    KNOWN_EVIDENCE_KINDS,
    DraftedBy,
    EvidenceItem,
    EvidenceKind,
    Proposal,
    ProposalOp,
    ReconciliationDecision,
    ReconciliationEntry,
    ReconciliationReport,
)
from canon.ingestion.reconciliation import (
    AcceptedStore,
    ExistingFact,
    InMemoryAcceptedStore,
    ReconciliationEngine,
)

__all__ = [
    "AcceptedStore",
    "AuditTrailWriter",
    "BuildResult",
    "ContextBuilder",
    "ContradictionNote",
    "DiffEmitter",
    "DiffFormat",
    "DiskEventLog",
    "DiskSnapshotStore",
    "DraftedBy",
    "EmissionResult",
    "EmittedDiff",
    "EventLog",
    "EvidenceItem",
    "EvidenceKind",
    "ExistingFact",
    "GrainDraft",
    "InMemoryAcceptedStore",
    "KNOWN_EVIDENCE_KINDS",
    "LLMDrafter",
    "NullLLMDrafter",
    "Proposal",
    "ProposalOp",
    "ReconciliationDecision",
    "ReconciliationEngine",
    "ReconciliationEntry",
    "ReconciliationReport",
    "SkippedEvidence",
    "SnapshotStore",
]
